#!/usr/bin/env python3
"""Generate catalog-seed.jsonl for merge-catalog.ts (~900 new objects)."""
import json
import re
import sys

def slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s[:64] or "item"

def entry(name, mass, category, wiki=None, qualifier=None):
    return {
        "name": name,
        "massKg": round(float(mass), 6),
        "category": category,
        "wikiTitle": wiki or name.replace(" ", "_"),
        "qualifier": qualifier or f"Typical {name.lower()}",
    }

items = []

def add_many(rows):
    for row in rows:
        items.append(entry(*row))

# --- Tiny (0.001–0.05 kg) ---
add_many([
    ("Honeybee", 0.0001, "animal", "Western_honey_bee"),
    ("Housefly", 0.000012, "animal", "Housefly"),
    ("Mosquito", 0.0000025, "animal", "Mosquito"),
    ("Fruit fly", 0.000001, "animal", "Drosophila_melanogaster"),
    ("Ant", 0.000003, "animal", "Ant"),
    ("Ladybug", 0.00002, "animal", "Coccinellidae"),
    ("Dragonfly", 0.0006, "animal", "Dragonfly"),
    ("Grasshopper", 0.002, "animal", "Grasshopper"),
    ("Cricket (insect)", 0.0005, "animal", "Cricket_(insect)"),
    ("Hummingbird egg", 0.0005, "animal", "Bird_egg"),
    ("Paper clip", 0.001, "other", "Paper_clip"),
    ("Postage stamp", 0.00005, "other", "Postage_stamp"),
    ("AA battery", 0.023, "household", "AA_battery"),
    ("AAA battery", 0.012, "household", "AAA_battery"),
    ("Pen", 0.01, "household", "Ballpoint_pen"),
    ("Pencil", 0.005, "household", "Pencil"),
    ("USB flash drive", 0.01, "household", "USB_flash_drive"),
    ("Cherry tomato", 0.017, "food", "Cherry_tomato"),
    ("Strawberry", 0.018, "food", "Strawberry"),
    ("Blueberry", 0.002, "food", "Blueberry"),
    ("Raspberry", 0.005, "food", "Raspberry"),
    ("Grape", 0.005, "food", "Grape"),
    ("Olive", 0.004, "food", "Olive"),
    ("Garlic clove", 0.005, "food", "Garlic"),
    ("Golf tee", 0.002, "sport", "Golf_tee"),
    ("Table tennis ball", 0.0027, "sport", "Table_tennis_ball"),
    ("Shuttlecock", 0.005, "sport", "Shuttlecock"),
    ("Dice", 0.005, "other", "Dice"),
    ("Coin (quarter)", 0.0057, "other", "Quarter_(United_States_coin)"),
    ("Wedding ring", 0.003, "other", "Wedding_ring"),
])

# --- Small (0.05–0.5 kg) ---
add_many([
    ("Lime", 0.06, "food", "Lime_(fruit)"),
    ("Lemon", 0.06, "food", "Lemon"),
    ("Kiwi fruit", 0.075, "food", "Kiwifruit"),
    ("Peach", 0.15, "food", "Peach"),
    ("Plum", 0.066, "food", "Plum"),
    ("Pear", 0.18, "food", "Pear"),
    ("Mango", 0.2, "food", "Mango"),
    ("Papaya", 0.5, "food", "Papaya"),
    ("Bell pepper", 0.12, "food", "Bell_pepper"),
    ("Cucumber", 0.2, "food", "Cucumber"),
    ("Zucchini", 0.2, "food", "Zucchini"),
    ("Onion", 0.15, "food", "Onion"),
    ("Head of lettuce", 0.3, "food", "Lettuce"),
    ("Broccoli head", 0.45, "food", "Broccoli"),
    ("Cauliflower", 0.6, "food", "Cauliflower"),
    ("Cabbage", 0.9, "food", "Cabbage"),
    ("Bagel", 0.1, "food", "Bagel"),
    ("Croissant", 0.06, "food", "Croissant"),
    ("Muffin", 0.11, "food", "Muffin"),
    ("Donut", 0.05, "food", "Doughnut"),
    ("Chocolate bar", 0.1, "food", "Chocolate_bar"),
    ("Candy bar", 0.05, "food", "Candy_bar"),
    ("Yogurt cup", 0.17, "food", "Yogurt"),
    ("Butter stick", 0.113, "food", "Butter"),
    ("Cheese wedge", 0.2, "food", "Cheese"),
    ("Hamster", 0.12, "animal", "Hamster"),
    ("Guinea pig", 0.9, "animal", "Guinea_pig"),
    ("Chinchilla", 0.6, "animal", "Chinchilla"),
    ("Ferret", 0.9, "animal", "Ferret"),
    ("Rat", 0.35, "animal", "Brown_rat"),
    ("Squirrel", 0.45, "animal", "Squirrel"),
    ("Pigeon", 0.35, "animal", "Rock_dove"),
    ("Crow", 0.45, "animal", "Crow"),
    ("Duck", 1.1, "animal", "Duck"),
    ("Chicken", 2.5, "animal", "Chicken"),
    ("Rooster", 3.0, "animal", "Rooster"),
    ("Turkey", 8.0, "animal", "Turkey_(bird)"),
    ("Parrot", 0.4, "animal", "Parrot"),
    ("Canary", 0.02, "animal", "Domestic_canary"),
    ("Goldfish", 0.35, "animal", "Goldfish"),
    ("Tennis racket", 0.3, "sport", "Tennis_racket"),
    ("Badminton racket", 0.09, "sport", "Badminton_racket"),
    ("Baseball bat", 0.9, "sport", "Baseball_bat"),
    ("Hockey stick", 0.5, "sport", "Hockey_stick"),
    ("Frisbee", 0.175, "sport", "Flying_disc"),
    ("Volleyball", 0.27, "sport", "Volleyball"),
    ("Rugby ball", 0.41, "sport", "Rugby_ball"),
    ("Lacrosse ball", 0.14, "sport", "Lacrosse_ball"),
    ("Softball", 0.19, "sport", "Softball"),
    ("Pair of scissors", 0.08, "household", "Scissors"),
    ("Hair dryer", 0.6, "household", "Hair_dryer"),
    ("Remote control", 0.1, "household", "Remote_control"),
    ("Coffee mug", 0.35, "household", "Coffee_mug"),
    ("Wine glass", 0.15, "household", "Wine_glass"),
    ("Plate", 0.4, "household", "Plate"),
    ("Mug", 0.3, "household", "Mug"),
])

# --- Medium-small (0.5–5 kg) ---
add_many([
    ("Water bottle (1L)", 1.0, "food", "Bottled_water"),
    ("Bag of sugar", 2.0, "food", "Sugar"),
    ("Bag of coffee", 1.0, "food", "Coffee"),
    ("Jar of peanut butter", 0.75, "food", "Peanut_butter"),
    ("Box of cereal", 0.5, "food", "Breakfast_cereal"),
    ("Frozen pizza", 0.45, "food", "Frozen_pizza"),
    ("Whole chicken (raw)", 1.8, "food", "Chicken_as_food"),
    ("Turkey breast", 3.0, "food", "Turkey_meat"),
    ("Salmon fillet", 0.2, "food", "Salmon"),
    ("Tuna can", 0.17, "food", "Canned_tuna"),
    ("Watermelon slice", 2.0, "food", "Watermelon"),
    ("Honeydew melon", 1.5, "food", "Honeydew_(melon)"),
    ("Cantaloupe", 1.2, "food", "Cantaloupe"),
    ("Eggplant", 0.25, "food", "Eggplant"),
    ("Sweet potato", 0.2, "food", "Sweet_potato"),
    ("Beet", 0.2, "food", "Beetroot"),
    ("Leek", 0.15, "food", "Leek"),
    ("Asparagus bunch", 0.5, "food", "Asparagus"),
    ("Green beans (bag)", 0.45, "food", "Green_bean"),
    ("Mushroom pack", 0.25, "food", "Mushroom"),
    ("Beagle", 12, "animal", "Beagle"),
    ("Bulldog", 22, "animal", "Bulldog"),
    ("Poodle", 8, "animal", "Poodle"),
    ("Dachshund", 9, "animal", "Dachshund"),
    ("German shepherd", 35, "animal", "German_Shepherd"),
    ("Labrador retriever", 30, "animal", "Labrador_Retriever"),
    ("Chihuahua", 2.5, "animal", "Chihuahua"),
    ("Border collie", 20, "animal", "Border_Collie"),
    ("Siamese cat", 4.0, "animal", "Siamese_cat"),
    ("Persian cat", 4.5, "animal", "Persian_cat"),
    ("Maine Coon", 7.0, "animal", "Maine_Coon"),
    ("Bengal cat", 5.5, "animal", "Bengal_cat"),
    ("Ragdoll cat", 6.0, "animal", "Ragdoll"),
    ("Alpaca", 70, "animal", "Alpaca"),
    ("Llama", 130, "animal", "Llama"),
    ("Donkey", 180, "animal", "Donkey"),
    ("Mule", 400, "animal", "Mule"),
    ("Zebra", 350, "animal", "Zebra"),
    ("Reindeer", 120, "animal", "Reindeer"),
    ("Deer", 90, "animal", "Deer"),
    ("Elk", 320, "animal", "Elk"),
    ("Bison", 700, "animal", "American_bison"),
    ("Antelope", 60, "animal", "Antelope"),
    ("Gazelle", 25, "animal", "Gazelle"),
    ("Cheetah", 50, "animal", "Cheetah"),
    ("Leopard", 55, "animal", "Leopard"),
    ("Jaguar", 85, "animal", "Jaguar"),
    ("Cougar", 70, "animal", "Cougar"),
    ("Lynx", 20, "animal", "Lynx"),
    ("Bobcat", 10, "animal", "Bobcat"),
    ("Hyena", 50, "animal", "Hyena"),
    ("Jackal", 10, "animal", "Jackal"),
    ("Coyote", 14, "animal", "Coyote"),
    ("Raccoon", 8, "animal", "Raccoon"),
    ("Skunk", 3.5, "animal", "Skunk"),
    ("Opossum", 3.0, "animal", "Opossum"),
    ("Porcupine", 8, "animal", "Porcupine"),
    ("Hedgehog", 0.8, "animal", "Hedgehog"),
    ("Koala", 10, "animal", "Koala"),
    ("Wombat", 28, "animal", "Wombat"),
    ("Platypus", 1.5, "animal", "Platypus"),
    ("Echidna", 4.5, "animal", "Echidna"),
    ("Sloth", 5, "animal", "Sloth"),
    ("Armadillo", 5, "animal", "Armadillo"),
    ("Anteater", 40, "animal", "Anteater"),
    ("Tapir", 250, "animal", "Tapir"),
    ("Camel", 650, "animal", "Camel"),
    ("Water buffalo", 700, "animal", "Water_buffalo"),
    ("Yak", 500, "animal", "Yak"),
    ("Seal", 85, "animal", "Pinniped"),
    ("Walrus", 1200, "animal", "Walrus"),
    ("Sea lion", 300, "animal", "Sea_lion"),
    ("Manatee", 450, "animal", "Manatee"),
    ("Orca", 5500, "animal", "Orca"),
    ("Beluga whale", 1400, "animal", "Beluga_whale"),
    ("Sperm whale", 35000, "animal", "Sperm_whale"),
    ("Humpback whale", 30000, "animal", "Humpback_whale"),
    ("Narwhal", 1600, "animal", "Narwhal"),
    ("Hammerhead shark", 230, "animal", "Hammerhead_shark"),
    ("Tiger shark", 385, "animal", "Tiger_shark"),
    ("Manta ray", 1200, "animal", "Manta_ray"),
    ("Stingray", 25, "animal", "Stingray"),
    ("Octopus", 15, "animal", "Octopus"),
    ("Squid", 20, "animal", "Squid"),
    ("Lobster", 0.5, "animal", "Lobster"),
    ("Crab", 0.5, "animal", "Crab"),
    ("Shrimp", 0.02, "animal", "Shrimp"),
    ("Oyster", 0.1, "animal", "Oyster"),
    ("Clam", 0.05, "animal", "Clam"),
    ("Starfish", 0.5, "animal", "Starfish"),
    ("Jellyfish", 0.2, "animal", "Jellyfish"),
    ("Sea horse", 0.01, "animal", "Seahorse"),
    ("Pufferfish", 1.0, "animal", "Tetraodontidae"),
    ("Swordfish", 200, "animal", "Swordfish"),
    ("Marlin", 200, "animal", "Marlin"),
    ("Tuna fish", 250, "animal", "Tuna"),
    ("Salmon (fish)", 5, "animal", "Salmon"),
    ("Trout", 2, "animal", "Trout"),
    ("Bass fish", 2, "animal", "Bass_(fish)"),
    ("Catfish", 15, "animal", "Catfish"),
    ("Piranha", 1.5, "animal", "Piranha"),
    ("Electric eel", 20, "animal", "Electric_eel"),
    ("Pike", 5, "animal", "Pike_(fish)"),
    ("Carp", 10, "animal", "Carp"),
    ("Koi", 5, "animal", "Koi"),
    ("Angelfish", 0.1, "animal", "Freshwater_angelfish"),
    ("Clownfish", 0.25, "animal", "Clownfish"),
    ("Barracuda", 15, "animal", "Barracuda"),
    ("Sturgeon", 50, "animal", "Sturgeon"),
    ("Alligator", 200, "animal", "Alligator"),
    ("Caiman", 40, "animal", "Caiman"),
    ("Komodo dragon", 70, "animal", "Komodo_dragon"),
    ("Iguana", 4, "animal", "Iguana"),
    ("Gecko", 0.05, "animal", "Gecko"),
    ("Chameleon", 0.15, "animal", "Chameleon"),
    ("Python", 50, "animal", "Pythonidae"),
    ("Boa constrictor", 15, "animal", "Boa_constrictor"),
    ("Cobra", 3, "animal", "Cobra"),
    ("Rattlesnake", 2, "animal", "Rattlesnake"),
    ("Viper", 2, "animal", "Viper"),
    ("Tortoise", 15, "animal", "Tortoise"),
    ("Box turtle", 0.5, "animal", "Box_turtle"),
    ("Sea turtle (green)", 150, "animal", "Green_sea_turtle"),
    ("Frog", 0.03, "animal", "Frog"),
    ("Toad", 0.08, "animal", "Toad"),
    ("Salamander", 0.02, "animal", "Salamander"),
    ("Newt", 0.01, "animal", "Newt"),
])

# --- Household / sport / vehicles (mixed masses) ---
add_many([
    ("Ironing board", 3.5, "household", "Ironing_board"),
    ("Iron", 1.2, "household", "Clothes_iron"),
    ("Blender", 3.0, "household", "Blender"),
    ("Food processor", 4.0, "household", "Food_processor"),
    ("Stand mixer", 5.5, "household", "Stand_mixer"),
    ("Rice cooker", 3.0, "household", "Rice_cooker"),
    ("Slow cooker", 4.5, "household", "Slow_cooker"),
    ("Air fryer", 5.0, "household", "Air_fryer"),
    ("Coffee maker", 3.5, "household", "Coffee_maker"),
    ("Espresso machine", 10, "household", "Espresso_machine"),
    ("Dishwasher", 50, "household", "Dishwasher"),
    ("Dryer", 60, "household", "Clothes_dryer"),
    ("Space heater", 4.0, "household", "Space_heater"),
    ("Fan", 3.0, "household", "Electric_fan"),
    ("Humidifier", 2.5, "household", "Humidifier"),
    ("Dehumidifier", 12, "household", "Dehumidifier"),
    ("Vacuum robot", 4.0, "household", "Robotic_vacuum_cleaner"),
    ("Steam mop", 3.0, "household", "Mop"),
    ("Broom", 0.5, "household", "Broom"),
    ("Mop bucket", 2.0, "household", "Mop"),
    ("Laundry basket", 1.0, "household", "Laundry_basket"),
    ("Trash can", 2.5, "household", "Waste_container"),
    ("Recycling bin", 3.0, "household", "Recycling_bin"),
    ("Step ladder", 5.0, "household", "Ladder"),
    ("Extension ladder", 15, "household", "Ladder"),
    ("Hammer", 0.5, "household", "Hammer"),
    ("Screwdriver set", 0.8, "household", "Screwdriver"),
    ("Wrench set", 2.0, "household", "Wrench"),
    ("Drill", 2.5, "household", "Power_drill"),
    ("Circular saw", 4.0, "household", "Circular_saw"),
    ("Chainsaw", 5.5, "household", "Chainsaw"),
    ("Lawn mower", 30, "household", "Lawn_mower"),
    ("Leaf blower", 5.0, "household", "Leaf_blower"),
    ("Garden hose reel", 8.0, "household", "Garden_hose"),
    ("Wheelbarrow", 15, "household", "Wheelbarrow"),
    ("Shovel", 2.0, "household", "Shovel"),
    ("Rake", 1.5, "household", "Rake"),
    ("Hose nozzle", 0.2, "household", "Garden_hose"),
    ("Picnic table", 35, "household", "Picnic_table"),
    ("Patio chair", 8.0, "household", "Garden_furniture"),
    ("Umbrella (patio)", 5.0, "household", "Umbrella"),
    ("Grill (charcoal)", 25, "household", "Barbecue_grill"),
    ("Propane grill", 45, "household", "Barbecue_grill"),
    ("Fire pit", 40, "household", "Fire_pit"),
    ("Sofa", 80, "household", "Couch"),
    ("Armchair", 25, "household", "Armchair"),
    ("Coffee table", 20, "household", "Coffee_table"),
    ("Dining table", 50, "household", "Table_(furniture)"),
    ("Dining chair", 5.0, "household", "Chair"),
    ("Bookshelf", 30, "household", "Bookshelf"),
    ("Wardrobe", 80, "household", "Wardrobe"),
    ("Dresser", 50, "household", "Chest_of_drawers"),
    ("Nightstand", 15, "household", "Nightstand"),
    ("Bed frame", 40, "household", "Bed_frame"),
    ("Pillow", 0.8, "household", "Pillow"),
    ("Comforter", 3.0, "household", "Comforter"),
    ("Blanket", 1.5, "household", "Blanket"),
    ("Area rug", 10, "household", "Rug"),
    ("Floor lamp", 5.0, "household", "Floor_lamp"),
    ("Desk lamp", 1.5, "household", "Desk_lamp"),
    ("Ceiling fan", 8.0, "household", "Ceiling_fan"),
    ("Mirror (wall)", 8.0, "household", "Mirror"),
    ("Picture frame", 1.0, "household", "Picture_frame"),
    ("Clock (wall)", 0.5, "household", "Clock"),
    ("Smoke detector", 0.2, "household", "Smoke_detector"),
    ("Fire extinguisher", 5.0, "household", "Fire_extinguisher"),
    ("First aid kit", 1.0, "household", "First_aid_kit"),
    ("Safe (small)", 15, "household", "Safe"),
    ("Suitcase", 4.0, "household", "Suitcase"),
    ("Backpack", 1.0, "household", "Backpack"),
    ("Handbag", 0.5, "household", "Handbag"),
    ("Umbrella (rain)", 0.4, "household", "Umbrella"),
    ("Rain boots", 1.2, "household", "Wellington_boot"),
    ("Winter coat", 1.5, "household", "Coat"),
    ("Jeans", 0.6, "household", "Jeans"),
    ("T-shirt", 0.2, "household", "T-shirt"),
    ("Soccer goal (portable)", 25, "sport", "Association_football"),
    ("Basketball hoop", 35, "sport", "Basketball_hoop"),
    ("Treadmill", 90, "sport", "Treadmill"),
    ("Exercise bike", 35, "sport", "Exercise_bicycle"),
    ("Elliptical machine", 80, "sport", "Elliptical_trainer"),
    ("Rowing machine", 45, "sport", "Indoor_rower"),
    ("Weight bench", 35, "sport", "Bench_press"),
    ("Barbell", 20, "sport", "Barbell"),
    ("Kettlebell", 16, "sport", "Kettlebell"),
    ("Yoga mat", 1.5, "sport", "Yoga_mat"),
    ("Foam roller", 0.5, "sport", "Foam_roller"),
    ("Jump rope", 0.3, "sport", "Jump_rope"),
    ("Boxing gloves", 0.5, "sport", "Boxing_glove"),
    ("Punching bag", 25, "sport", "Punching_bag"),
    ("Surfboard", 3.0, "sport", "Surfboard"),
    ("Snowboard", 4.0, "sport", "Snowboard"),
    ("Pair of skis", 5.0, "sport", "Ski"),
    ("Ice skates", 2.0, "sport", "Ice_skate"),
    ("Roller skates", 2.5, "sport", "Roller_skates"),
    ("Helmet (bike)", 0.3, "sport", "Bicycle_helmet"),
    ("Scooter", 3.5, "vehicle", "Kick_scooter"),
    ("Rollerblades", 2.0, "sport", "Inline_skates"),
    ("Tent (camping)", 4.0, "sport", "Tent"),
    ("Sleeping bag", 1.5, "sport", "Sleeping_bag"),
    ("Camping stove", 1.0, "sport", "Portable_stove"),
    ("Cooler", 8.0, "sport", "Cooler"),
    ("Fishing rod", 0.3, "sport", "Fishing_rod"),
    ("Golf bag", 4.0, "sport", "Golf_bag"),
    ("Golf club set", 8.0, "sport", "Golf_club"),
    ("Archery bow", 1.0, "sport", "Bow_and_arrow"),
    ("Quiver of arrows", 0.8, "sport", "Quiver"),
    ("Pool cue", 0.6, "sport", "Cue_stick"),
    ("Ping pong table", 70, "sport", "Table_tennis"),
    ("Pool table", 320, "sport", "Billiard_table"),
    ("Dartboard", 2.0, "sport", "Dartboard"),
    ("Croquet set", 5.0, "sport", "Croquet"),
    ("Badminton net", 3.0, "sport", "Badminton"),
    ("Volleyball net", 5.0, "sport", "Volleyball"),
    ("Compact car", 1200, "vehicle", "Compact_car"),
    ("Sports car", 1400, "vehicle", "Sports_car"),
    ("SUV", 2000, "vehicle", "Sport_utility_vehicle"),
    ("Minivan", 2100, "vehicle", "Minivan"),
    ("Convertible", 1500, "vehicle", "Convertible"),
    ("Electric car", 1800, "vehicle", "Electric_car"),
    ("Hybrid car", 1600, "vehicle", "Hybrid_vehicle"),
    ("Police car", 1800, "vehicle", "Police_car"),
    ("Ambulance", 3500, "vehicle", "Ambulance"),
    ("Fire truck", 12000, "vehicle", "Fire_engine"),
    ("Garbage truck", 15000, "vehicle", "Garbage_truck"),
    ("Delivery van", 3500, "vehicle", "Van"),
    ("City bus", 12000, "vehicle", "Bus"),
    ("Double-decker bus", 15000, "vehicle", "Double-decker_bus"),
    ("Tram", 20000, "vehicle", "Tram"),
    ("Subway car", 35000, "vehicle", "Passenger_rail_car"),
    ("Train locomotive", 120000, "vehicle", "Locomotive"),
    ("Freight train car", 30000, "vehicle", "Freight_car"),
    ("Tractor", 5000, "vehicle", "Tractor"),
    ("Combine harvester", 12000, "vehicle", "Combine_harvester"),
    ("Bulldozer", 15000, "vehicle", "Bulldozer"),
    ("Excavator", 20000, "vehicle", "Excavator"),
    ("Crane (mobile)", 40000, "vehicle", "Crane_(machine)"),
    ("Dump truck", 15000, "vehicle", "Dump_truck"),
    ("Cement mixer truck", 18000, "vehicle", "Concrete_mixer"),
    ("Tanker truck", 20000, "vehicle", "Tank_truck"),
    ("RV", 4500, "vehicle", "Recreational_vehicle"),
    ("Camper trailer", 2000, "vehicle", "Travel_trailer"),
    ("Boat (small motor)", 800, "vehicle", "Motorboat"),
    ("Sailboat", 2500, "vehicle", "Sailboat"),
    ("Yacht", 15000, "vehicle", "Yacht"),
    ("Cruise ship", 50000000, "vehicle", "Cruise_ship"),
    ("Ferry", 5000000, "vehicle", "Ferry"),
    ("Cargo ship", 20000000, "vehicle", "Cargo_ship"),
    ("Container ship", 100000000, "vehicle", "Container_ship"),
    ("Submarine", 3000000, "vehicle", "Submarine"),
    ("Aircraft carrier", 90000000, "vehicle", "Aircraft_carrier"),
    ("Helicopter", 2500, "vehicle", "Helicopter"),
    ("Small airplane", 1000, "vehicle", "Light_aircraft"),
    ("Commercial jet", 75000, "vehicle", "Airliner"),
    ("Glider", 300, "vehicle", "Glider_(aircraft)"),
    ("Hot air balloon", 500, "vehicle", "Hot_air_balloon"),
    ("Paraglider", 15, "vehicle", "Paragliding"),
    ("Hang glider", 25, "vehicle", "Hang_gliding"),
    ("Rocket (small)", 500, "vehicle", "Rocket"),
    ("Satellite", 1000, "vehicle", "Satellite"),
    ("Space shuttle", 78000, "vehicle", "Space_Shuttle"),
    ("Moon rover", 210, "vehicle", "Lunar_Roving_Vehicle"),
    ("ATV", 350, "vehicle", "All-terrain_vehicle"),
    ("Snowmobile", 250, "vehicle", "Snowmobile"),
    ("Segway", 50, "vehicle", "Segway"),
    ("Electric scooter", 15, "vehicle", "Electric_scooter"),
    ("Unicycle", 5, "vehicle", "Unicycle"),
    ("Tricycle", 8, "vehicle", "Tricycle"),
    ("Wheelchair", 15, "vehicle", "Wheelchair"),
    ("Stroller", 10, "vehicle", "Baby_transport"),
    ("Shopping cart", 15, "vehicle", "Shopping_cart"),
    ("Hand truck", 8, "vehicle", "Hand_truck"),
    ("Pallet jack", 80, "vehicle", "Pallet_jack"),
    ("Steam locomotive", 90000, "vehicle", "Steam_locomotive"),
    ("Cable car", 2000, "vehicle", "Cable_car"),
    ("Funicular car", 5000, "vehicle", "Funicular"),
])

# --- Nature / minerals / plants ---
add_many([
    ("Boulder", 500, "nature", "Boulder"),
    ("River rock", 2.0, "nature", "Rock_(geology)"),
    ("Sandbag", 20, "nature", "Sandbag"),
    ("Hay bale", 25, "nature", "Hay"),
    ("Log", 50, "nature", "Log"),
    ("Pine tree", 8000, "nature", "Pine"),
    ("Palm tree", 5000, "nature", "Arecaceae"),
    ("Bonsai tree", 2.0, "nature", "Bonsai"),
    ("Rose bush", 3.0, "nature", "Rose"),
    ("Sunflower", 0.15, "nature", "Sunflower"),
    ("Cactus", 5.0, "nature", "Cactus"),
    ("Fern", 0.5, "nature", "Fern"),
    ("Moss patch", 0.1, "nature", "Moss"),
    ("Lichen", 0.05, "nature", "Lichen"),
    ("Mushroom (wild)", 0.1, "nature", "Mushroom"),
    ("Acorn", 0.006, "nature", "Acorn"),
    ("Pine cone", 0.05, "nature", "Pine_cone"),
    ("Seashell", 0.02, "nature", "Seashell"),
    ("Coral piece", 0.5, "nature", "Coral"),
    ("Driftwood", 3.0, "nature", "Driftwood"),
    ("Ice block", 1.0, "nature", "Ice"),
    ("Snowball", 0.5, "nature", "Snow"),
    ("Sandcastle", 5.0, "nature", "Sand"),
    ("Granite slab", 50, "nature", "Granite"),
    ("Marble block", 60, "nature", "Marble"),
    ("Limestone rock", 30, "nature", "Limestone"),
    ("Sandstone", 25, "nature", "Sandstone"),
    ("Coal chunk", 1.0, "nature", "Coal"),
    ("Iron ore sample", 2.0, "nature", "Iron_ore"),
    ("Copper ore", 2.0, "nature", "Copper"),
    ("Silver bar (small)", 1.0, "other", "Silver"),
    ("Platinum coin", 0.007, "other", "Platinum"),
    ("Diamond (1 carat)", 0.0002, "other", "Diamond"),
    ("Ruby gemstone", 0.0003, "other", "Ruby"),
    ("Emerald", 0.0003, "other", "Emerald"),
    ("Pearl", 0.0001, "other", "Pearl"),
    ("Meteorite fragment", 0.5, "nature", "Meteorite"),
    ("Fossil", 2.0, "nature", "Fossil"),
    ("Amber piece", 0.01, "nature", "Amber"),
    ("Volcanic rock", 1.0, "nature", "Volcanic_rock"),
    ("Geode", 0.5, "nature", "Geode"),
    ("Quartz crystal", 0.1, "nature", "Quartz"),
    ("Amethyst", 0.05, "nature", "Amethyst"),
    ("Topsoil bag", 20, "nature", "Soil"),
    ("Compost bag", 15, "nature", "Compost"),
    ("Mulch bag", 18, "nature", "Mulch"),
    ("Fertilizer bag", 25, "nature", "Fertilizer"),
    ("Seeds packet", 0.05, "nature", "Seed"),
    ("Potted plant", 3.0, "nature", "Houseplant"),
    ("Orchid plant", 0.5, "nature", "Orchid"),
    ("Bamboo stalk", 2.0, "nature", "Bamboo"),
    ("Wheat sheaf", 0.5, "nature", "Wheat"),
    ("Corn stalk", 0.3, "nature", "Maize"),
    ("Rice plant", 0.2, "nature", "Rice"),
    ("Cotton boll", 0.005, "nature", "Cotton"),
    ("Maple tree", 10000, "nature", "Maple"),
    ("Willow tree", 6000, "nature", "Willow"),
    ("Birch tree", 5000, "nature", "Birch"),
    ("Redwood tree", 500000, "nature", "Sequoioideae"),
    ("Baobab tree", 15000, "nature", "Adansonia"),
    ("Banyan tree", 20000, "nature", "Banyan"),
    ("Cherry blossom tree", 3000, "nature", "Cherry_blossom"),
    ("Apple tree", 4000, "nature", "Apple_tree"),
    ("Banana plant", 50, "nature", "Banana"),
    ("Vineyard grape cluster", 0.2, "food", "Vitis_vinifera"),
    ("Tea bag box", 0.2, "food", "Tea"),
    ("Spice jar", 0.1, "food", "Spice"),
    ("Salt shaker", 0.2, "food", "Salt"),
    ("Pepper grinder", 0.3, "food", "Black_pepper"),
    ("Olive oil bottle", 0.9, "food", "Olive_oil"),
    ("Vinegar bottle", 0.5, "food", "Vinegar"),
    ("Ketchup bottle", 0.5, "food", "Ketchup"),
    ("Mustard jar", 0.3, "food", "Mustard_(condiment)"),
    ("Mayonnaise jar", 0.4, "food", "Mayonnaise"),
    ("Hot sauce bottle", 0.2, "food", "Hot_sauce"),
    ("Soy sauce bottle", 0.3, "food", "Soy_sauce"),
    ("Maple syrup bottle", 0.5, "food", "Maple_syrup"),
    ("Honey jar", 0.5, "food", "Honey"),
    ("Jam jar", 0.35, "food", "Fruit_preserves"),
    ("Nutella jar", 0.4, "food", "Nutella"),
    ("Instant noodles pack", 0.09, "food", "Instant_noodle"),
    ("Mac and cheese box", 0.2, "food", "Macaroni_and_cheese"),
    ("Granola bar box", 0.4, "food", "Granola"),
    ("Potato chips bag", 0.15, "food", "Potato_chip"),
    ("Popcorn bag", 0.1, "food", "Popcorn"),
    ("Pretzel bag", 0.2, "food", "Pretzel"),
    ("Trail mix bag", 0.25, "food", "Trail_mix"),
    ("Protein bar", 0.06, "food", "Protein_bar"),
    ("Energy drink can", 0.35, "food", "Energy_drink"),
    ("Iced tea bottle", 0.5, "food", "Iced_tea"),
    ("Orange juice carton", 1.0, "food", "Orange_juice"),
    ("Coconut water carton", 0.5, "food", "Coconut_water"),
    ("Sparkling water case", 9.0, "food", "Carbonated_water"),
    ("Baby formula tin", 0.6, "food", "Infant_formula"),
    ("Dog food bag", 15, "food", "Dog_food"),
    ("Cat food bag", 4.0, "food", "Cat_food"),
    ("Bird seed bag", 2.0, "food", "Bird_food"),
    ("Fish food container", 0.1, "food", "Fish_food"),
])

# --- Dog breeds ---
add_many([
    ("Akita", 40, "animal", "Akita_(dog)"),
    ("Samoyed", 25, "animal", "Samoyed_(dog)"),
    ("Husky", 23, "animal", "Siberian_Husky"),
    ("Malamute", 38, "animal", "Alaskan_Malamute"),
    ("Saint Bernard", 75, "animal", "St._Bernard_(dog)"),
    ("Great Dane", 70, "animal", "Great_Dane"),
    ("Mastiff", 80, "animal", "English_Mastiff"),
    ("Newfoundland", 60, "animal", "Newfoundland_dog"),
    ("Bernese mountain dog", 45, "animal", "Bernese_Mountain_Dog"),
    ("Rottweiler", 50, "animal", "Rottweiler"),
    ("Doberman", 35, "animal", "Dobermann"),
    ("Boxer", 30, "animal", "Boxer_(dog)"),
    ("Dalmatian", 27, "animal", "Dalmatian_(dog)"),
    ("Greyhound", 32, "animal", "Greyhound"),
    ("Whippet", 12, "animal", "Whippet"),
    ("Irish wolfhound", 55, "animal", "Irish_Wolfhound"),
    ("Scottish terrier", 10, "animal", "Scottish_Terrier"),
    ("Yorkshire terrier", 3, "animal", "Yorkshire_Terrier"),
    ("Shih Tzu", 5.5, "animal", "Shih_Tzu"),
    ("Pug", 8, "animal", "Pug"),
    ("Corgi", 12, "animal", "Pembroke_Welsh_Corgi"),
    ("Australian shepherd", 25, "animal", "Australian_Shepherd"),
    ("Cocker spaniel", 13, "animal", "Cocker_Spaniel"),
    ("Springer spaniel", 20, "animal", "English_Springer_Spaniel"),
    ("Pointer", 28, "animal", "Pointer_(dog_breed)"),
    ("Setter", 30, "animal", "Setter"),
    ("Weimaraner", 32, "animal", "Weimaraner"),
    ("Vizsla", 25, "animal", "Vizsla"),
    ("Bloodhound", 45, "animal", "Bloodhound"),
    ("Basset hound", 25, "animal", "Basset_Hound"),
    ("Beagle mix", 13, "animal", "Beagle"),
    ("Pit bull", 25, "animal", "American_Pit_Bull_Terrier"),
    ("Staffordshire terrier", 15, "animal", "Staffordshire_Bull_Terrier"),
    ("Shar Pei", 22, "animal", "Shar_Pei"),
    ("Chow Chow", 28, "animal", "Chow_Chow"),
    ("Airedale terrier", 23, "animal", "Airedale_Terrier"),
    ("Boston terrier", 11, "animal", "Boston_Terrier"),
    ("French bulldog", 12, "animal", "French_Bulldog"),
    ("English bulldog", 23, "animal", "Bulldog"),
    ("Miniature schnauzer", 7, "animal", "Miniature_Schnauzer"),
    ("Standard poodle", 25, "animal", "Poodle"),
    ("Toy poodle", 3, "animal", "Toy_Poodle"),
    ("Bichon frise", 5, "animal", "Bichon_Frises"),
    ("Maltese dog", 3, "animal", "Maltese_(dog)"),
    ("Papillon dog", 4, "animal", "Papillon_(dog)"),
    ("Pomeranian", 2, "animal", "Pomeranian_(dog)"),
    ("Collie", 27, "animal", "Collie"),
    ("Shetland sheepdog", 8, "animal", "Shetland_Sheepdog"),
    ("Old English sheepdog", 35, "animal", "Old_English_Sheepdog"),
])

# --- Birds ---
add_many([
    ("Barn swallow", 0.02, "animal", "Barn_swallow"),
    ("Blue jay", 0.085, "animal", "Blue_jay"),
    ("Cardinal bird", 0.045, "animal", "Northern_cardinal"),
    ("Robin", 0.077, "animal", "American_robin"),
    ("Woodpecker", 0.08, "animal", "Woodpecker"),
    ("Hummingbird (ruby)", 0.004, "animal", "Ruby-throated_hummingbird"),
    ("Flamingo", 3.5, "animal", "Flamingo"),
    ("Pelican", 5.5, "animal", "Pelican"),
    ("Seagull", 0.9, "animal", "Gull"),
    ("Albatross", 8.5, "animal", "Albatross"),
    ("Puffin", 0.5, "animal", "Puffin"),
    ("Peacock", 5.0, "animal", "Peafowl"),
    ("Swan", 11, "animal", "Swan"),
    ("Goose", 4.5, "animal", "Goose"),
    ("Penguin (Adelie)", 4.5, "animal", "Adelie_penguin"),
    ("Penguin (King)", 15, "animal", "King_penguin"),
    ("Penguin (Macaroni)", 5.5, "animal", "Macaroni_penguin"),
    ("Toucan", 0.5, "animal", "Toucan"),
    ("Macaw", 1.0, "animal", "Macaw"),
    ("Cockatoo", 0.9, "animal", "Cockatoo"),
    ("Budgerigar", 0.035, "animal", "Budgerigar"),
    ("Cockatiel", 0.09, "animal", "Cockatiel"),
    ("Lovebird", 0.05, "animal", "Lovebird"),
    ("Falcon", 0.9, "animal", "Falcon"),
    ("Hawk", 1.2, "animal", "Hawk"),
    ("Eagle (golden)", 5.0, "animal", "Golden_eagle"),
    ("Owl (great horned)", 1.4, "animal", "Great_horned_owl"),
    ("Vulture", 6.0, "animal", "Vulture"),
    ("Stork", 4.0, "animal", "Stork"),
    ("Heron", 1.5, "animal", "Heron"),
    ("Crane bird", 5.0, "animal", "Crane_(bird)"),
    ("Quail", 0.15, "animal", "Quail"),
    ("Pheasant", 1.2, "animal", "Pheasant"),
    ("Partridge", 0.4, "animal", "Partridge"),
    ("Grouse", 0.5, "animal", "Grouse"),
    ("Woodcock", 0.3, "animal", "Woodcock"),
    ("Sandpiper", 0.05, "animal", "Sandpiper"),
    ("Kingfisher", 0.04, "animal", "Kingfisher"),
    ("Swallow", 0.02, "animal", "Swallow"),
    ("Swift (bird)", 0.04, "animal", "Swift_(bird)"),
    ("Nightingale", 0.02, "animal", "Nightingale"),
    ("Starling", 0.08, "animal", "Starling"),
    ("Magpie", 0.2, "animal", "Magpie"),
    ("Raven", 1.0, "animal", "Raven"),
    ("Jackdaw", 0.25, "animal", "Western_jackdaw"),
    ("Finch", 0.02, "animal", "Finch"),
    ("Sparrowhawk", 0.15, "animal", "Sparrowhawk"),
    ("Kestrel", 0.2, "animal", "Common_kestrel"),
    ("Condor", 12, "animal", "Condor"),
    ("Kiwi bird", 2.5, "animal", "Kiwi_(bird)"),
    ("Cassowary", 45, "animal", "Cassowary"),
    ("Emu", 40, "animal", "Emu"),
    ("Rhea", 25, "animal", "Rhea_(bird)"),
])

# --- Insects & small creatures ---
add_many([
    ("Butterfly", 0.0005, "animal", "Butterfly"),
    ("Moth", 0.0003, "animal", "Moth"),
    ("Beetle", 0.0002, "animal", "Beetle"),
    ("Wasp", 0.0001, "animal", "Wasp"),
    ("Bee (bumble)", 0.0006, "animal", "Bumblebee"),
    ("Caterpillar", 0.0005, "animal", "Caterpillar"),
    ("Snail", 0.01, "animal", "Snail"),
    ("Slug", 0.005, "animal", "Slug"),
    ("Earthworm", 0.005, "animal", "Earthworm"),
    ("Spider", 0.0003, "animal", "Spider"),
    ("Tarantula", 0.085, "animal", "Tarantula"),
    ("Scorpion", 0.06, "animal", "Scorpion"),
    ("Centipede", 0.005, "animal", "Centipede"),
    ("Millipede", 0.01, "animal", "Millipede"),
    ("Praying mantis", 0.0005, "animal", "Mantis"),
    ("Stick insect", 0.0003, "animal", "Phasmatodea"),
    ("Firefly", 0.00002, "animal", "Firefly"),
    ("Cicada", 0.002, "animal", "Cicada"),
    ("Locust", 0.002, "animal", "Locust"),
    ("Termite", 0.000002, "animal", "Termite"),
    ("Flea", 0.000001, "animal", "Flea"),
    ("Tick", 0.000001, "animal", "Tick"),
    ("Bed bug", 0.000005, "animal", "Bed_bug"),
    ("Cockroach", 0.00005, "animal", "Cockroach"),
    ("Silverfish", 0.00001, "animal", "Silverfish"),
    ("Dragonfly nymph", 0.001, "animal", "Dragonfly"),
    ("Water strider", 0.00001, "animal", "Gerridae"),
    ("Cricket (field)", 0.0005, "animal", "Gryllidae"),
    ("Leafhopper", 0.000005, "animal", "Leafhopper"),
    ("Aphid", 0.000001, "animal", "Aphid"),
])

# --- Dinosaurs & prehistoric ---
add_many([
    ("Tyrannosaurus rex", 8000, "animal", "Tyrannosaurus"),
    ("Triceratops", 6000, "animal", "Triceratops"),
    ("Stegosaurus", 5000, "animal", "Stegosaurus"),
    ("Brachiosaurus", 35000, "animal", "Brachiosaurus"),
    ("Velociraptor", 15, "animal", "Velociraptor"),
    ("Spinosaurus", 7500, "animal", "Spinosaurus"),
    ("Ankylosaurus", 6000, "animal", "Ankylosaurus"),
    ("Parasaurolophus", 2500, "animal", "Parasaurolophus"),
    ("Diplodocus", 15000, "animal", "Diplodocus"),
    ("Allosaurus", 1500, "animal", "Allosaurus"),
    ("Apatosaurus", 20000, "animal", "Apatosaurus"),
    ("Pterodactyl", 25, "animal", "Pterosaur"),
    ("Mammoth", 6000, "animal", "Mammoth"),
    ("Woolly rhinoceros", 2000, "animal", "Woolly_rhinoceros"),
    ("Sabre-toothed cat", 200, "animal", "Machairodus"),
    ("Giant ground sloth", 1500, "animal", "Megatherium"),
    ("Dodo", 10, "animal", "Dodo"),
    ("Passenger pigeon", 0.34, "animal", "Passenger_pigeon"),
    ("Megalodon tooth", 0.6, "nature", "Megalodon"),
    ("Trilobite fossil", 0.05, "nature", "Trilobite"),
])

# --- Musical instruments ---
add_many([
    ("Acoustic guitar", 2.5, "household", "Acoustic_guitar"),
    ("Electric guitar", 3.5, "household", "Electric_guitar"),
    ("Bass guitar", 4.0, "household", "Bass_guitar"),
    ("Violin", 0.5, "household", "Violin"),
    ("Viola", 0.6, "household", "Viola"),
    ("Cello", 3.0, "household", "Cello"),
    ("Double bass", 10, "household", "Double_bass"),
    ("Harp", 35, "household", "Harp"),
    ("Flute", 0.3, "household", "Flute"),
    ("Clarinet", 0.7, "household", "Clarinet"),
    ("Saxophone", 2.5, "household", "Saxophone"),
    ("Trumpet", 1.2, "household", "Trumpet"),
    ("Trombone", 1.5, "household", "Trombone"),
    ("French horn", 2.0, "household", "French_horn"),
    ("Tuba", 8.0, "household", "Tuba"),
    ("Drum kit", 25, "household", "Drum_kit"),
    ("Snare drum", 3.0, "household", "Snare_drum"),
    ("Cymbal", 2.0, "household", "Cymbal"),
    ("Bongo drums", 3.0, "household", "Bongo_drum"),
    ("Conga drum", 5.0, "household", "Conga"),
    ("Xylophone", 4.0, "household", "Xylophone"),
    ("Marimba", 80, "household", "Marimba"),
    ("Accordion", 9.0, "household", "Accordion"),
    ("Harmonica", 0.05, "household", "Harmonica"),
    ("Ukulele", 0.5, "household", "Ukulele"),
    ("Banjo", 2.5, "household", "Banjo"),
    ("Mandolin", 0.7, "household", "Mandolin"),
    ("Synthesizer", 8.0, "household", "Synthesizer"),
    ("Keyboard (music)", 12, "household", "Electronic_keyboard"),
    ("DJ turntable", 5.0, "household", "Turntable"),
    ("Microphone", 0.5, "household", "Microphone"),
    ("Speaker cabinet", 20, "household", "Loudspeaker"),
    ("Gong", 5.0, "household", "Gong"),
    ("Triangle (instrument)", 0.2, "household", "Triangle_(musical_instrument)"),
    ("Tambourine", 0.3, "household", "Tambourine"),
    ("Bagpipes", 3.0, "household", "Bagpipes"),
    ("Didgeridoo", 2.0, "household", "Didgeridoo"),
    ("Sitar", 2.0, "household", "Sitar"),
    ("Tabla", 3.0, "household", "Tabla"),
    ("Pan flute", 0.2, "household", "Pan_flute"),
])

# --- Electronics & tech ---
add_many([
    ("Desktop computer", 8.0, "household", "Desktop_computer"),
    ("Computer monitor", 5.0, "household", "Computer_monitor"),
    ("Mechanical keyboard", 1.2, "household", "Computer_keyboard"),
    ("Computer mouse", 0.1, "household", "Computer_mouse"),
    ("Webcam", 0.2, "household", "Webcam"),
    ("Router", 0.5, "household", "Router_(computing)"),
    ("Modem", 0.4, "household", "Modem"),
    ("External hard drive", 0.3, "household", "Hard_disk_drive"),
    ("SSD drive", 0.05, "household", "Solid-state_drive"),
    ("Graphics card", 1.5, "household", "Graphics_card"),
    ("Power supply unit", 2.0, "household", "Power_supply_unit_(computer)"),
    ("CPU cooler", 0.8, "household", "Computer_cooling"),
    ("Server rack unit", 20, "household", "Rack_unit"),
    ("Smartwatch", 0.05, "household", "Smartwatch"),
    ("Fitness tracker", 0.03, "household", "Activity_tracker"),
    ("Wireless earbuds", 0.05, "household", "Headphones"),
    ("Over-ear headphones", 0.3, "household", "Headphones"),
    ("Bluetooth speaker", 0.6, "household", "Loudspeaker"),
    ("Soundbar", 3.0, "household", "Soundbar"),
    ("Projector", 3.0, "household", "Video_projector"),
    ("Drone (consumer)", 0.8, "household", "Unmanned_aerial_vehicle"),
    ("Action camera", 0.15, "household", "Action_camera"),
    ("DSLR camera", 0.8, "household", "Digital_single-lens_reflex_camera"),
    ("Camera lens", 0.6, "household", "Camera_lens"),
    ("Tripod", 1.5, "household", "Tripod_(photography)"),
    ("VR headset", 0.5, "household", "Virtual_reality_headset"),
    ("Game controller", 0.3, "household", "Game_controller"),
    ("Arcade cabinet", 120, "household", "Arcade_cabinet"),
    ("Pinball machine", 130, "household", "Pinball"),
    ("3D printer", 10, "household", "3D_printing"),
    ("Robot vacuum", 4.0, "household", "Robotic_vacuum_cleaner"),
    ("Smart thermostat", 0.2, "household", "Thermostat"),
    ("Doorbell camera", 0.2, "household", "Video_doorbell"),
    ("NAS device", 3.0, "household", "Network-attached_storage"),
    ("USB hub", 0.1, "household", "USB_hub"),
    ("Laptop charger", 0.3, "household", "Battery_charger"),
    ("Power bank", 0.3, "household", "Power_bank"),
    ("E-reader", 0.2, "household", "E-reader"),
    ("Calculator", 0.1, "household", "Calculator"),
    ("Digital scale", 1.5, "household", "Weighing_scale"),
])

# --- More food & drink ---
add_many([
    ("Sushi roll", 0.15, "food", "Sushi"),
    ("Burrito", 0.35, "food", "Burrito"),
    ("Taco", 0.12, "food", "Taco"),
    ("Hot dog", 0.1, "food", "Hot_dog"),
    ("Hamburger", 0.2, "food", "Hamburger"),
    ("Cheeseburger", 0.25, "food", "Cheeseburger"),
    ("Pizza slice", 0.15, "food", "Pizza"),
    ("French fries carton", 0.15, "food", "French_fries"),
    ("Onion rings", 0.12, "food", "Onion_ring"),
    ("Chicken nuggets", 0.1, "food", "Chicken_nugget"),
    ("Fish and chips", 0.4, "food", "Fish_and_chips"),
    ("Ramen bowl", 0.5, "food", "Ramen"),
    ("Pho bowl", 0.6, "food", "Pho"),
    ("Pad thai", 0.4, "food", "Pad_thai"),
    ("Curry dish", 0.45, "food", "Curry"),
    ("Stir fry", 0.4, "food", "Stir_frying"),
    ("Salad bowl", 0.35, "food", "Salad"),
    ("Soup bowl", 0.4, "food", "Soup"),
    ("Steak dinner", 0.35, "food", "Steak"),
    ("Pork chop", 0.2, "food", "Pork_chop"),
    ("Lamb chop", 0.15, "food", "Lamb_and_mutton"),
    ("Bacon pack", 0.45, "food", "Bacon"),
    ("Sausage pack", 0.5, "food", "Sausage"),
    ("Deli ham", 0.25, "food", "Ham"),
    ("Smoked salmon pack", 0.2, "food", "Smoked_salmon"),
    ("Shrimp cocktail", 0.2, "food", "Shrimp_cocktail"),
    ("Lobster tail", 0.15, "food", "Lobster"),
    ("Crab legs", 0.5, "food", "Crab"),
    ("Oysters dozen", 0.6, "food", "Oyster"),
    ("Sushi platter", 0.8, "food", "Sushi"),
    ("Birthday cake", 1.5, "food", "Birthday_cake"),
    ("Wedding cake tier", 5.0, "food", "Wedding_cake"),
    ("Cupcake", 0.05, "food", "Cupcake"),
    ("Cookie jar", 0.3, "food", "Cookie"),
    ("Brownie tray", 0.4, "food", "Chocolate_brownie"),
    ("Pie", 0.8, "food", "Pie"),
    ("Cheesecake", 1.2, "food", "Cheesecake"),
    ("Ice cream tub", 0.5, "food", "Ice_cream"),
    ("Popsicle box", 0.3, "food", "Ice_pop"),
    ("Frozen vegetables bag", 0.45, "food", "Frozen_food"),
    ("Frozen berries bag", 0.35, "food", "Berry"),
    ("Smoothie bottle", 0.4, "food", "Smoothie"),
    ("Protein shake", 0.35, "food", "Protein_shake"),
    ("Latte cup", 0.35, "food", "Latte"),
    ("Espresso cup", 0.03, "food", "Espresso"),
    ("Tea pot", 0.8, "food", "Teapot"),
    ("French press", 0.5, "food", "French_press"),
    ("Wine case", 10, "food", "Wine"),
    ("Beer six-pack", 2.0, "food", "Beer"),
    ("Whiskey bottle", 1.2, "food", "Whisky"),
    ("Vodka bottle", 1.0, "food", "Vodka"),
    ("Gin bottle", 1.0, "food", "Gin"),
    ("Tequila bottle", 1.1, "food", "Tequila"),
    ("Champagne bottle", 1.5, "food", "Champagne"),
    ("Sake bottle", 0.7, "food", "Sake"),
    ("Kombucha bottle", 0.4, "food", "Kombucha"),
    ("Coconut milk can", 0.4, "food", "Coconut_milk"),
    ("Tomato sauce jar", 0.6, "food", "Tomato_sauce"),
    ("Pasta box", 0.5, "food", "Pasta"),
    ("Rice bag (10 lb)", 4.5, "food", "Rice"),
    ("Quinoa bag", 0.45, "food", "Quinoa"),
    ("Lentils bag", 0.45, "food", "Lentil"),
    ("Chickpeas can", 0.4, "food", "Chickpea"),
    ("Black beans can", 0.4, "food", "Black_bean"),
    ("Olive jar", 0.35, "food", "Olive"),
    ("Pickle jar", 0.5, "food", "Pickled_cucumber"),
    ("Salsa jar", 0.4, "food", "Salsa_(food)"),
    ("Hummus tub", 0.25, "food", "Hummus"),
    ("Guacamole tub", 0.2, "food", "Guacamole"),
    ("Tortilla pack", 0.35, "food", "Tortilla"),
    ("Naan bread pack", 0.3, "food", "Naan"),
    ("Pita bread pack", 0.25, "food", "Pita"),
    ("Croissant pack", 0.25, "food", "Croissant"),
    ("Baguette", 0.25, "food", "Baguette"),
    ("Sourdough loaf", 0.5, "food", "Sourdough"),
    ("Rye bread loaf", 0.45, "food", "Rye_bread"),
    ("Gluten-free bread", 0.4, "food", "Gluten-free_diet"),
    ("Granola bag", 0.4, "food", "Granola"),
    ("Oatmeal container", 0.9, "food", "Oatmeal"),
    ("Corn flakes box", 0.35, "food", "Corn_flakes"),
    ("Wheat cereal box", 0.4, "food", "Breakfast_cereal"),
    ("Pop-tarts box", 0.35, "food", "Pop-Tarts"),
    ("Peanut butter jar", 0.75, "food", "Peanut_butter"),
    ("Almond butter jar", 0.5, "food", "Almond_butter"),
    ("Cashews tin", 0.45, "food", "Cashew"),
    ("Almonds bag", 0.45, "food", "Almond"),
    ("Walnuts bag", 0.35, "food", "Walnut"),
    ("Pistachios bag", 0.3, "food", "Pistachio"),
    ("Raisins box", 0.15, "food", "Raisin"),
    ("Dried apricots bag", 0.2, "food", "Apricot"),
    ("Dates pack", 0.25, "food", "Date_(fruit)"),
    ("Fig pack", 0.2, "food", "Common_fig"),
    ("Prunes pack", 0.2, "food", "Prune"),
    ("Gummy bears bag", 0.15, "food", "Gummy_bear"),
    ("Licorice bag", 0.12, "food", "Licorice_(confectionery)"),
    ("Marshmallows bag", 0.2, "food", "Marshmallow"),
    ("Cotton candy", 0.03, "food", "Cotton_candy"),
    ("Lollipop", 0.015, "food", "Lollipop"),
    ("Chewing gum pack", 0.03, "food", "Chewing_gum"),
    ("Breath mints tin", 0.05, "food", "Breath_mint"),
])

# --- Marine mammals & more animals ---
add_many([
    ("Narwhal tusk (display)", 10, "nature", "Narwhal"),
    ("Dugong", 400, "animal", "Dugong"),
    ("Sea otter", 25, "animal", "Sea_otter"),
    ("River otter", 10, "animal", "Otter"),
    ("Mink", 1.0, "animal", "American_mink"),
    ("Badger", 12, "animal", "Badger"),
    ("Wolverine", 15, "animal", "Wolverine"),
    ("Marten", 1.5, "animal", "Marten"),
    ("Stoat", 0.3, "animal", "Stoat"),
    ("Weasel", 0.2, "animal", "Weasel"),
    ("Mongoose", 1.5, "animal", "Mongoose"),
    ("Meerkat", 0.7, "animal", "Meerkat"),
    ("Lemur", 3.0, "animal", "Lemur"),
    ("Capuchin monkey", 3.5, "animal", "Capuchin_monkey"),
    ("Howler monkey", 8.0, "animal", "Howler_monkey"),
    ("Spider monkey", 7.0, "animal", "Spider_monkey"),
    ("Baboon", 30, "animal", "Baboon"),
    ("Mandrill", 35, "animal", "Mandrill"),
    ("Gibbon", 7.0, "animal", "Gibbon"),
    ("Orangutan", 75, "animal", "Orangutan"),
    ("Chimpanzee", 50, "animal", "Chimpanzee"),
    ("Bonobo", 40, "animal", "Bonobo"),
    ("Proboscis monkey", 20, "animal", "Proboscis_monkey"),
    ("Panda", 100, "animal", "Giant_panda"),
    ("Red panda", 5.0, "animal", "Red_panda"),
    ("Sun bear", 50, "animal", "Sun_bear"),
    ("Black bear", 150, "animal", "American_black_bear"),
    ("Brown bear", 300, "animal", "Brown_bear"),
    ("Sloth bear", 140, "animal", "Sloth_bear"),
    ("Spectacled bear", 130, "animal", "Spectacled_bear"),
    ("Arctic fox", 4.0, "animal", "Arctic_fox"),
    ("Fennec fox", 1.5, "animal", "Fennec_fox"),
    ("Bat (fruit)", 0.15, "animal", "Fruit_bat"),
    ("Vampire bat", 0.04, "animal", "Vampire_bat"),
    ("Flying squirrel", 0.15, "animal", "Flying_squirrel"),
    ("Chipmunk", 0.12, "animal", "Chipmunk"),
    ("Prairie dog", 1.5, "animal", "Prairie_dog"),
    ("Groundhog", 4.0, "animal", "Groundhog"),
    ("Marmot", 4.0, "animal", "Marmot"),
    ("Capybara", 50, "animal", "Capybara"),
    ("Agouti", 3.0, "animal", "Agouti"),
    ("Pacarana", 15, "animal", "Pacarana"),
    ("Nutria", 8.0, "animal", "Coypu"),
    ("Muskrat", 1.5, "animal", "Muskrat"),
    ("Bandicoot", 1.5, "animal", "Bandicoot"),
    ("Quokka", 3.0, "animal", "Quokka"),
    ("Wallaby", 15, "animal", "Wallaby"),
    ("Tasmanian devil", 8.0, "animal", "Tasmanian_devil"),
    ("Thylacine (estimate)", 25, "animal", "Thylacine"),
    ("Bandicoot rat", 0.5, "animal", "Bandicoot"),
])

# --- Tools, office, misc ---
add_many([
    ("Stapler", 0.3, "household", "Stapler"),
    ("Hole punch", 0.5, "household", "Hole_punch"),
    ("Paper shredder", 8.0, "household", "Paper_shredder"),
    ("Whiteboard", 10, "household", "Whiteboard"),
    ("Cork board", 2.0, "household", "Bulletin_board"),
    ("Filing cabinet", 35, "household", "Filing_cabinet"),
    ("Copy machine", 80, "household", "Photocopier"),
    ("Fax machine", 10, "household", "Fax"),
    ("Laminator", 5.0, "household", "Laminator"),
    ("Label maker", 0.5, "household", "Label_printer"),
    ("Paper ream", 2.5, "household", "Paper"),
    ("Binder", 0.5, "household", "Ring_binder"),
    ("Notebook", 0.3, "household", "Notebook"),
    ("Clipboard", 0.2, "household", "Clipboard"),
    ("Desk organizer", 0.5, "household", "Desk"),
    ("Trash shredder bin", 3.0, "household", "Waste_container"),
    ("Water cooler", 15, "household", "Water_cooler"),
    ("Coffee urn", 5.0, "household", "Coffee_urn"),
    ("Vending machine", 300, "household", "Vending_machine"),
    ("ATM machine", 800, "household", "Automated_teller_machine"),
    ("Parking meter", 40, "other", "Parking_meter"),
    ("Traffic light", 15, "other", "Traffic_light"),
    ("Stop sign", 5.0, "other", "Stop_sign"),
    ("Fire hydrant", 80, "other", "Fire_hydrant"),
    ("Manhole cover", 50, "other", "Manhole"),
    ("Park bench", 50, "other", "Bench"),
    ("Bus stop shelter", 200, "other", "Bus_stop"),
    ("Phone booth", 150, "other", "Telephone_booth"),
    ("Mailbox", 15, "other", "Post_box"),
    ("Flagpole", 20, "other", "Flagpole"),
    ("Statue (small)", 50, "other", "Statue"),
    ("Fountain (garden)", 200, "other", "Fountain"),
    ("Wind chime", 0.5, "other", "Wind_chime"),
    ("Garden gnome", 2.0, "other", "Garden_gnome"),
    ("Bird bath", 15, "other", "Bird_bath"),
    ("Bird feeder", 1.5, "other", "Bird_feeder"),
    ("Compost bin", 10, "other", "Compost"),
    ("Rain barrel", 20, "other", "Rain_barrel"),
    ("Greenhouse panel", 5.0, "other", "Greenhouse"),
    ("Shed (garden)", 150, "other", "Shed"),
    ("Fence post", 8.0, "other", "Fence"),
    ("Gate (metal)", 25, "other", "Gate"),
    ("Mailbox package", 0.5, "other", "Package"),
    ("Shipping pallet", 15, "other", "Pallet"),
    ("Cardboard box (large)", 0.5, "other", "Cardboard_box"),
    ("Wooden crate", 10, "other", "Crate"),
    ("Barrel", 15, "other", "Barrel"),
    ("Oil drum", 180, "other", "Drum_(container)"),
    ("Propane tank", 18, "other", "Propane"),
    ("Oxygen tank", 5.0, "other", "Oxygen_tank"),
    ("Firewood bundle", 10, "nature", "Firewood"),
    ("Charcoal bag", 8.0, "nature", "Charcoal"),
    ("Kindling bundle", 2.0, "nature", "Kindling"),
    ("Tiki torch", 1.5, "other", "Tiki_torch"),
    ("Lantern", 0.5, "other", "Lantern"),
    ("Flashlight", 0.2, "other", "Flashlight"),
    ("Headlamp", 0.15, "other", "Headlamp"),
    ("Camping lantern", 0.5, "other", "Lantern"),
    ("Compass", 0.05, "other", "Compass"),
    ("Binoculars", 0.6, "other", "Binoculars"),
    ("Telescope", 5.0, "other", "Telescope"),
    ("Microscope", 3.0, "other", "Microscope"),
    ("Globe", 2.0, "other", "Globe"),
    ("World atlas", 1.5, "other", "Atlas"),
    ("Chess set", 0.8, "other", "Chess"),
    ("Board game box", 1.0, "other", "Board_game"),
    ("Puzzle box", 0.5, "other", "Jigsaw_puzzle"),
    ("Lego set box", 0.8, "other", "Lego"),
    ("Toy car", 0.2, "other", "Toy"),
    ("Teddy bear", 0.3, "other", "Teddy_bear"),
    ("Doll", 0.3, "other", "Doll"),
    ("Action figure", 0.15, "other", "Action_figure"),
    ("Rubik's cube", 0.1, "other", "Rubik's_Cube"),
    ("Yo-yo", 0.05, "other", "Yo-yo"),
    ("Kite", 0.2, "other", "Kite"),
    ("Balloon", 0.01, "other", "Balloon"),
    ("Piñata", 0.5, "other", "Pinata"),
    ("Christmas tree", 15, "other", "Christmas_tree"),
    ("Wreath", 1.0, "other", "Wreath"),
    ("Jack-o-lantern", 3.0, "other", "Jack-o'-lantern"),
    ("Easter basket", 0.5, "other", "Easter_basket"),
    ("Wedding ring box", 0.05, "other", "Wedding_ring"),
    ("Trophy", 2.0, "other", "Trophy"),
    ("Medal", 0.05, "other", "Medal"),
    ("Certificate frame", 0.5, "other", "Certificate"),
    ("Diploma frame", 0.8, "other", "Diploma"),
    ("Urn (decorative)", 2.0, "other", "Urn"),
    ("Hourglass", 0.3, "other", "Hourglass"),
    ("Sundial", 5.0, "other", "Sundial"),
    ("Weather vane", 3.0, "other", "Weather_vane"),
    ("Barometer", 0.5, "other", "Barometer"),
    ("Thermometer", 0.05, "other", "Thermometer"),
    ("Rain gauge", 0.3, "other", "Rain_gauge"),
    ("Anemometer", 1.0, "other", "Anemometer"),
    ("Lightning rod", 3.0, "other", "Lightning_rod"),
    ("Solar panel", 20, "other", "Solar_panel"),
    ("Wind turbine (small)", 50, "other", "Wind_turbine"),
    ("Battery pack (EV)", 450, "vehicle", "Electric_vehicle_battery"),
    ("Car battery", 15, "vehicle", "Automotive_battery"),
    ("Tire", 10, "vehicle", "Tire"),
    ("Car wheel", 12, "vehicle", "Wheel"),
    ("Hubcap", 0.5, "vehicle", "Hubcap"),
    ("License plate", 0.5, "vehicle", "Vehicle_registration_plate"),
    ("Car jack", 3.0, "vehicle", "Jack_(device)"),
    ("Jumper cables", 2.0, "vehicle", "Jumper_cables"),
    ("Roof rack", 8.0, "vehicle", "Roof_rack"),
    ("Bike rack", 10, "vehicle", "Bicycle_carrier"),
    ("Trailer hitch", 15, "vehicle", "Trailer_hitch"),
    ("Boat anchor", 10, "vehicle", "Anchor"),
    ("Life jacket", 0.8, "sport", "Life_jacket"),
    ("Life raft", 25, "sport", "Life_raft"),
    ("Flare gun", 0.5, "sport", "Flare_gun"),
    ("Whistle", 0.02, "sport", "Whistle"),
    ("Stopwatch", 0.05, "sport", "Stopwatch"),
    ("Scoreboard", 200, "sport", "Scoreboard"),
    ("Referee flag", 0.1, "sport", "Flag"),
    ("Megaphone", 0.5, "sport", "Megaphone"),
    ("Coach clipboard", 0.3, "sport", "Clipboard"),
    ("Chalk line reel", 0.5, "sport", "Chalk_line"),
    ("Measuring tape", 0.3, "household", "Tape_measure"),
    ("Level tool", 0.5, "household", "Spirit_level"),
    ("Stud finder", 0.2, "household", "Stud_finder"),
    ("Multimeter", 0.3, "household", "Multimeter"),
    ("Soldering iron", 0.3, "household", "Soldering_iron"),
    ("Heat gun", 0.8, "household", "Heat_gun"),
    ("Workbench", 40, "household", "Workbench"),
    ("Vise", 5.0, "household", "Vise"),
    ("Anvil", 50, "household", "Anvil"),
    ("Forge (small)", 80, "household", "Forge"),
    ("Kiln (pottery)", 50, "household", "Kiln"),
    ("Pottery wheel", 30, "household", "Potter's_wheel"),
    ("Sewing machine", 8.0, "household", "Sewing_machine"),
    ("Spinning wheel", 5.0, "household", "Spinning_wheel"),
    ("Loom", 25, "household", "Loom"),
    ("Quilting frame", 10, "household", "Quilting"),
    ("Knitting needles", 0.05, "household", "Knitting_needle"),
    ("Yarn skein", 0.1, "household", "Yarn"),
    ("Fabric bolt", 2.0, "household", "Textile"),
    ("Mannequin", 15, "household", "Mannequin"),
    ("Dress form", 5.0, "household", "Dress_form"),
    ("Ironing mat", 0.5, "household", "Ironing_board"),
    ("Lint roller", 0.1, "household", "Lint_roller"),
    ("Clothes hanger pack", 0.3, "household", "Clothes_hanger"),
    ("Garment bag", 0.3, "household", "Garment_bag"),
    ("Steamer", 2.0, "household", "Clothes_steamer"),
    ("Shoe rack", 3.0, "household", "Shoe_rack"),
    ("Coat rack", 2.0, "household", "Coat_rack"),
    ("Umbrella stand", 1.0, "household", "Umbrella_stand"),
    ("Key bowl", 0.2, "household", "Bowl"),
    ("Door mat", 1.5, "household", "Doormat"),
    ("Welcome sign", 1.0, "household", "Sign"),
    ("House number plaque", 0.5, "other", "House_number"),
    ("Door knocker", 0.5, "other", "Door_knocker"),
    ("Doorbell", 0.2, "other", "Doorbell"),
    ("House key", 0.01, "other", "Key_(lock)"),
    ("Padlock", 0.2, "other", "Padlock"),
    ("Combination lock", 0.15, "other", "Combination_lock"),
    ("Bike lock", 1.0, "vehicle", "Bicycle_lock"),
    ("Chain lock", 2.0, "vehicle", "Chain"),
    ("Cable lock", 0.5, "vehicle", "Lock_(security_device)"),
])

# Deduplicate by slug
seen = set()
unique = []
for it in items:
    sid = slug(it["name"])
    base = sid
    n = 2
    while sid in seen:
        sid = f"{base}-{n}"
        n += 1
    seen.add(sid)
    it["id"] = sid
    unique.append(it)

out = sys.argv[1] if len(sys.argv) > 1 else "src/data/catalog-seed.jsonl"
with open(out, "w") as f:
    for it in unique:
        f.write(json.dumps(it) + "\n")

print(f"Wrote {len(unique)} seed entries to {out}", file=sys.stderr)
